### ISSUE TITLE
安装yubisaki-shell，结果显示fsevents@1.2.4不兼容win32，yubisaki命令找不到

### ISSUE THREAD

**Issue by qiannianchong25** [Bloss/yubisaki-shell#2]
$ yarn global add yubisaki-shell
yarn global v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "yubisaki-shell@1.0.11" with binaries:
      - yubisaki
Done in 37.75s.

Administrator@WIN-7I7TNFVTVU6 MINGW64 /e/vueBlog
$ yubisaki post -p docs/hello --page index.md
bash: yubisaki: command not found

**Comment by stickmy** [comment]
可以留下你的 node 版本，系统版本以及 yarn 版本吗

**Comment by qiannianchong25** [comment]
$ yarn -v
1.7.0

$ node -v
v8.11.2

**Comment by qiannianchong25** [comment]
$ yarn -v
1.7.0

$ node -v
v8.11.2
系统：win7 64位

**Comment by stickmy** [comment]
尝试将 `node` 版本升级到 8.1.4，或者降级到8以下
